### ISSUE TITLE
"= true" instead of "==true"

### ISSUE THREAD

**Issue by lolbot-iichan** [JenniBee/openquest#1]
https://github.com/JenniBee/openquest/blob/b8b7f0fba8bd71dd049a35dd18c8c75bfa615186/Open%20Quest%20Wintermute/data/scenes/room2/scr/scene_init.script#L33

**Comment by JenniBee** [comment]
I've just updated the code. Thanks a bunch for spotting that. :)

**Comment by lolbot-iichan** [comment]
I guess I would never spot this with naked eye.
Real story is like this: I've written a simple Wintermute decompiler tool and tested it on some games.
Script failed to decompile this exact line with stack underflow, that's how I found it =)

Thanks for fixing this.
There is another suspicious line at https://github.com/JenniBee/openquest/blob/f5e1c2dccf32747c7d3ebd99a008e426a7fcf79d/Open%20Quest%20Wintermute/data/scenes/triangle/scr/exit.script#L10 , however === should be similar to == in that case, so I'm not sure if I need to create and issue. Funny thing is that Wintermute docs does not mention === operator, but it is supported.
